// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBukSHhK6YTDyaHJeWVzg966J_u8KDMIuY',
    appId: '1:651469209749:web:a36937fc85130ff9c45b9c',
    messagingSenderId: '651469209749',
    projectId: 'mi-entrenamiento-9f4a8',
    authDomain: 'mi-entrenamiento-9f4a8.firebaseapp.com',
    storageBucket: 'mi-entrenamiento-9f4a8.firebasestorage.app',
    measurementId: 'G-LGHEYKVNCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4C0-75dWh9eh6SuwRO4sNSVEmDoXeNi4',
    appId: '1:651469209749:android:35e35b383d91555fc45b9c',
    messagingSenderId: '651469209749',
    projectId: 'mi-entrenamiento-9f4a8',
    storageBucket: 'mi-entrenamiento-9f4a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY1rJhHO500hBtbQwLFXfvnz8XH5IPNmc',
    appId: '1:651469209749:ios:ede802233ee59c59c45b9c',
    messagingSenderId: '651469209749',
    projectId: 'mi-entrenamiento-9f4a8',
    storageBucket: 'mi-entrenamiento-9f4a8.firebasestorage.app',
    iosBundleId: 'com.example.miEntrenamiento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY1rJhHO500hBtbQwLFXfvnz8XH5IPNmc',
    appId: '1:651469209749:ios:ede802233ee59c59c45b9c',
    messagingSenderId: '651469209749',
    projectId: 'mi-entrenamiento-9f4a8',
    storageBucket: 'mi-entrenamiento-9f4a8.firebasestorage.app',
    iosBundleId: 'com.example.miEntrenamiento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBukSHhK6YTDyaHJeWVzg966J_u8KDMIuY',
    appId: '1:651469209749:web:eb8b20953d7f4a08c45b9c',
    messagingSenderId: '651469209749',
    projectId: 'mi-entrenamiento-9f4a8',
    authDomain: 'mi-entrenamiento-9f4a8.firebaseapp.com',
    storageBucket: 'mi-entrenamiento-9f4a8.firebasestorage.app',
    measurementId: 'G-CLQZXX32MR',
  );
}
